server:
  port: 8081

spring:
  application:
    name: house-service
  datasource:
    url: jdbc:postgresql://localhost:5432/house-db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
