server:
  port: 8083

spring:
  application:
    name: device-service
  datasource:
    url: jdbc:postgresql://localhost:5434/device-db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true